### ISSUE TITLE
stop running block and stop runtimes not work, 

### ISSUE THREAD

**Issue by zhaihao** [twibiral/obsidian-execute-code#281] opened 2023-07-28 07:13 UTC
Thank you for creating such an awesome plugin.but I ran into some issues. 

os：macOS
language：python

https://github.com/twibiral/obsidian-execute-code/assets/4202032/1256363b-3e2e-4a2c-93bd-648ed8c13af1

**Comment by jamesbtan** [comment] 2024-05-29 03:48
This is old, but I think the issue is that pkill -P also returns 1 if there are no children processes to kill.
Then since it is a non-zero exit code, it throws an error even though it should be able to proceed smoothly.

Maybe we can ignore the 1 error code for pkill?

**Comment by jancbeck** [comment] 2024-05-29 07:24
Just wanted to confirm that the issue is still here. When I click the spinner nothing happens. When I click the trashcan in the pane, console prints :

> node:internal/errors:867 Uncaught (in promise) Error: Command failed: pkill -P 50125
    at __node_internal_genericNodeError (node:internal/errors:867:15)
    at checkExecSyncError (node:child_process:911:11)
    at execSync (node:child_process:983:15)
    at node:electron/js2c/asar_bundle:2:12758
    at killWithChildren_default (plugin:execute-code:12309:39)
    at eval (plugin:execute-code:12377:7)
    at new Promise (<anonymous>)
    at NodeJSExecutor.stop (plugin:execute-code:12373:12)
    at HTMLButtonElement.eval (plugin:execute-code:12940:53)

**Comment by jamesbtan** [comment] 2024-05-30 06:56
Yes. When you close the runtime, the plugin also tries to close any child processes that the runtime may have spawned.

However, if your runtime has no child process, then the pkill will return an error code of 1 to signify that no processes were found.
The execSync helper function throws an error on all non-zero error codes though, so it logs the error and stops before it kills the runtime itself.

I have made a pull request with a fix that works for me, you can try to make the change yourself and see if it resolves the issue for you.

**Comment by twibiral** [comment] 2024-05-30 22:53
Fixed with new release [version 1.12.0](https://github.com/twibiral/obsidian-execute-code/releases/tag/1.12.0)

**Closed by twibiral** 2024-05-30 22:53 UTC
