### ISSUE TITLE
Lower 'Clear' button is covering the result.

### ISSUE THREAD

**Issue by CodAffection** [twibiral/obsidian-execute-code#36] opened 2022-08-03 04:22 UTC
After code block execution, the result is covered with 'clear' button.
Could you add space in between?

**Comment by twibiral** [comment] 2022-08-03 16:45
This shouldn't happen. Can you send me the code you executed when this happended?

**Comment by NiuXZi** [comment] 2022-08-07 07:18
> This shouldn't happen. Can you send me the code you executed when this happended?

![image](https://user-images.githubusercontent.com/61132813/183279836-31599761-9b50-456c-aeac-ca5fd05f8fa7.png)
Like this

**Comment by CodAffection** [comment] 2022-08-07 07:20
Yes

**Comment by twibiral** [comment] 2022-08-10 21:57
> > This shouldn't happen. Can you send me the code you executed when this happended?
> 
> ![image](https://user-images.githubusercontent.com/61132813/183279836-31599761-9b50-456c-aeac-ca5fd05f8fa7.png) Like this

I cannot reproduce this unfortunately. What Theme are you using? Is there anything that may interferes with the plugin installed for your Obsidian app?

**Comment by CodAffection** [comment] 2022-08-11 11:14
It is a theme called Primary.

**Comment by NiuXZi** [comment] 2022-08-28 10:59
> > > This shouldn't happen. Can you send me the code you executed when this happended?
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/61132813/183279836-31599761-9b50-456c-aeac-ca5fd05f8fa7.png) Like this
> 
> I cannot reproduce this unfortunately. What Theme are you using? Is there anything that may interferes with the plugin installed for your Obsidian app?
Obsidian Nord. Like it.
![image](https://user-images.githubusercontent.com/61132813/187070652-2c025743-0ad3-4cfe-b95a-f5c43fd4094b.png)

**Comment by twibiral** [comment] 2022-08-29 21:08
Fixed by Release [0.10.0](https://github.com/twibiral/obsidian-execute-code/releases/tag/0.10.0)

The clear button is hidden until you hover over the code block with this update.

**Closed by twibiral** 2022-08-29 21:08 UTC
Labels: bug, enhancement

**Comment by twibiral** [comment] 2022-08-29 21:10
If you have other problems or ideas to improve the plugin do not hesitate to open a new issue or reopen this one.
