### ISSUE TITLE
[BUG] Input element shows up for a split second

### ISSUE THREAD

**Issue by milan338** [twibiral/obsidian-execute-code#96] opened 2022-10-05 12:13 UTC
When running a c++ code block, I can see an input element appear for a split second then disappear.

**Comment by chlohal** [comment] 2022-10-05 13:05
This is intended behaviour (on my part, at least). There's no way to detect if a process is waiting for input, so the input element is shown whenever the code is running

**Comment by chlohal** [comment] 2022-10-05 13:06
It could be fixed in a hacky manner by waiting 500ms to show the input element; I'll try that out & see if it helps 👍

**Comment by chlohal** [comment] 2022-10-14 12:50
Is this fixed/closable?

**Comment by milan338** [comment] 2022-10-14 12:55
I think so, it's no longer an issue on my end.

**Comment by chlohal** [comment] 2022-10-14 15:16
Wonderful! It's no longer a problem for me either; thank you, Milan! :+1:

**Closed by chlohal** 2022-10-14 15:16 UTC
Labels: bug
