### ISSUE TITLE
[FR] Different Syntax for Codeblock Identifier

### ISSUE THREAD

**Issue by zcysxy** [twibiral/obsidian-execute-code#62] opened 2022-09-20 18:42 UTC
Thanks for this amazing plugin!

Global code injection is a game changer. However, I am a little unsure about the future-proofness of the syntax, i.e., `pre-`, `post-`, and `run-` prefixes. Have you considered the convention used in other Markdown apps like

- [R Markdown](https://rmarkdown.rstudio.com/lesson-3.html)
- [Markdown Preview Enhanced](https://shd101wyy.github.io/markdown-preview-enhanced/#/code-chunk)

Then the syntax could be:

~~~markdown
```python {run pre}
import numpy as np
```
~~~

By using this, the Markdown parser still recognizes it as a Python codeblock, hence things like syntax highlighting persist.
Also this syntax is more flexible and allows combinations.

**Comment by milan338** [comment] 2022-09-21 00:20
This is definitely doable. I didn't consider this approach when adding the feature as I first tried a DOM traversal, though Obsidian removes anything after a space in the HTML. However anything like `python {run pre}` does show up in the file contents, and it shouldn't be too hard to rework the existing implementation. This means we can remove the custom markdown rendering for pre and post blocks, because obsidian will ignore this extra syntax anyway. This should also potentially allow adding a temporary uuid to the code block when running, to avoid the issue with duplicate code blocks mentioned in #61 . The other modifiers mentioned on those two sites linked could be good to add, especially the ability to hide code blocks from preview mode.

**Comment by twibiral** [comment] 2022-09-21 08:33
Its mqybe also possible to not just compare the content of code blocks but also the line they appear

**Comment by milan338** [comment] 2022-09-21 14:34
The problem is that we don't really have a way to get the line on which they appear. If we could, there wouldn't be a reason to compare contents at all, but we only know about the element in the DOM when we run it, and there's no link between the DOM and the file contents. I've tried alternative approaches, and the most promising approach looks like temporarily adding an id to the code block in the file, so we have information about the executed block in the file. I haven't yet found a way to modify the file at the position of the code block, if anyone has ideas or knows about any relevant obsidian apis please share them.

**Comment by twibiral** [comment] 2022-10-13 19:12
@milan338 I would like to close this issue if you agree

**Comment by milan338** [comment] 2022-10-14 04:38
Yeah sure I think you can close it

**Comment by zcysxy** [comment] 2022-10-14 04:53
Thanks for the great work! Is `run` for executing in live Preview implemented as a block argument 👀? I don't see it in the readme

**Comment by milan338** [comment] 2022-10-14 04:59
It hasn't been added as a block argument because obsidian ignores the code block arguments when registering code block processors, so we can't register a custom code block processor in this way (since that's how running in live preview currently works with `registerMarkdownCodeBlockProcessor`). I don't know of a different way we could do this, if anyone has any ideas please share them.

**Comment by zcysxy** [comment] 2022-10-14 05:26
> It hasn't been added as a block argument because obsidian ignores the code block arguments when registering code block processors, so we can't register a custom code block processor in this way (since that's how running in live preview currently works with `registerMarkdownCodeBlockProcessor`). I don't know of a different way we could do this, if anyone has any ideas please share them.

Got it 👍

**Closed** 2022-10-14 13:59 UTC
Labels: enhancement, features request

**Comment by mayurankv** [comment] 2022-10-28 10:32
Out of curiosity, could you replace the default `lang` code block processor? Would this have adverse effects - presumably no longer working in reading mode?

**Comment by twibiral** [comment] 2022-11-05 14:29
I am not completely sure what you want to achieve exactly. Of course, you can replace the language processors of this plugin in the source code of this plugin but this is of no use.

Do you want to register new code block processors that can be defined by the user? I think this is possible but hard to implement and would require the plugin to inject code into the source code during runtime which you should never ever do.

But feel free to create a new issue and explain your idea in more depth.
