### ISSUE TITLE
PowerShell on MacOS and Linux

### ISSUE THREAD

**Issue by berot3** [twibiral/obsidian-execute-code#107] opened 2022-10-08 14:05 UTC
Hi! 🙋‍♂️ 

In the Readme it says that for powershell windows is required?

I wanted to try this plugin on Mac, but now I first wanted to ask why it is not compatible and if there is something that can be done about it.

Thanks!

**Comment by twibiral** [comment] 2022-10-08 14:17
Hi, PowerShell is mostly used in Windows but you can download and install it on Mac too. It will probably work then. If you want to use your normal macos shell you can simply use `shell` or `bash` instead of `powershell` as your code block language.

Does this answer your question?

**Comment by berot3** [comment] 2022-10-09 18:15
Thanks I'll try that. Than the Readme is a bit misleading 😉

> Requirements: Set the path to your preferred shell in the settings. Default is Powershell. (Only on Windows)

**Comment by twibiral** [comment] 2022-10-13 17:10
You can create three different kinds of code blocks: `shell`, `bash`, and `powershell`.

If you use `powershell` the plugin will try to use PowerShell. Otherwise the plugin tries to use bash / shell / zsh.

**Comment by twibiral** [comment] 2022-10-13 19:07
Please close this issue if your problem is resolved @berot3

**Comment by berot3** [comment] 2022-10-18 15:37
I am on MacOS and I get this for `run-powershell`

```
/bin/sh: powershell: command not found

```

but in sh/bash I can successfully switch to powershell by using `pwsh`:

```
sh-3.2$ pwsh
PowerShell 7.2.6
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.
```

Also in the plugin-settings I replaced the path with `pwsh` to see if it works, but it did not.

**Comment by chlohal** [comment] 2022-10-18 18:27
What version of MacOS are you on? This might be the same root cause as #87-- could you follow the same debugging strategies as in that issue, and see if it helps?

**Comment by twibiral** [comment] 2022-10-18 18:46
The command for powershell is set to "powershell" as default. 

> sh-3.2$ pwsh
> PowerShell 7.2.6
> Copyright (c) Microsoft Corporation.
> 
> https://aka.ms/powershell
> Type 'help' to get help.

This looks like the correct command for powershell on UNIX is `pwsh` instead. Try to change the powershell command in the plugin settings to from `powershell` to `pwsh`.

**Comment by berot3** [comment] 2022-10-19 08:14
> This looks like the correct command for powershell on UNIX is `pwsh` instead. Try to change the powershell command in the plugin settings to from `powershell` to `pwsh`.

Yes, that's what I wanted to say, I did. Getting this error:

```
/bin/sh: pwsh: command not found
```

(instead of `/bin/sh: powershell: command not found`)

---

@chlohal I am on macOS Ventura 13.0

**Comment by berot3** [comment] 2022-10-19 09:47
I got it working like this:

in plugin-settings use this as powershell-path: "`/usr/local/bin/pwsh`"

I'd like to note that I installed PowerShell though Homebrew.

I then can run 

```powershell
which pwsh

echo "Hello World!"

Write-Host "no newline test " -NoNewline 
Write-Host "second string"
---
/usr/local/microsoft/powershell/7/pwsh
Hello World!
no newline test second string
```

**Comment by berot3** [comment] 2022-10-19 09:47
I guess this is the solution?

**Closed as completed** 2022-10-19 14:14 UTC

**Comment by berot3** [comment] 2022-10-19 15:33
Thanks, @twibiral and @chlohal !
