### ISSUE TITLE
Inconsistency with python version and modules (wrong python binary being run ?)

### ISSUE THREAD

**Issue by mateusfbsoares** [twibiral/obsidian-execute-code#38] opened 2022-08-11 19:19 UTC
On options, I have set python path to be '/user/bin/python3'. 
When I run the following code
```
import sys
print(sys.executable)
```
it prints ```/usr/bin/python3```

---

```/usr/bin/python3``` is version 3.10.4 and has matplotlib installed (as you can see on the image below) 
![image](https://user-images.githubusercontent.com/43099047/184220846-eed9a0b1-b0d9-411e-aa62-1a5156e0fe6b.png)

---

However, when running any script on obsidian-execute-code with the python parameter "--version" set under the plugin options, the result is always Python ```3.6.9```, and when importing matplotlib, it says ```ModuleNotFoundError: No module named 'matplotlib'```

---

Any idea of what might solve? Thanks!

**Comment by twibiral** [comment] 2022-08-16 23:49
Try removing the --version option

**Comment by mateusfbsoares** [comment] 2022-08-16 23:59
Without the --version option, If I try to import matplotlib, I get the error ```ModuleNotFoundError: No module named 'matplotlib'```

![image](https://user-images.githubusercontent.com/43099047/185004883-4c5f97b1-aa12-4bb0-b328-fb69c15a59ba.png)
(no "--version" option passed as argument)

![image](https://user-images.githubusercontent.com/43099047/185004839-4289fdaf-35de-4147-862a-c1d9ab226a0e.png)
but error persists

however, on my terminal, I can import matplotlib using the python binary I'm passing on the python path option withtout errors: 
![image](https://user-images.githubusercontent.com/43099047/185005010-81c66c7e-61a1-42c9-8879-b3bb2e90e485.png)
![image](https://user-images.githubusercontent.com/43099047/185005059-12a5eba2-86cc-4189-9077-c42fed0e755b.png)

I strongly believe the execute-code plugin is not using the python binary I'm passing on the options as the python path

**Comment by twibiral** [comment] 2022-08-24 11:12
Could you try setting the path to another python installation on your system? I can't reproduce this error...

**Comment by twibiral** [comment] 2022-08-29 21:12
I made some changes in Release [0.10.0](https://github.com/twibiral/obsidian-execute-code/releases/tag/0.10.0). Do your problems still occur?

**Comment by pspiagicw** [comment] 2022-08-31 12:40
@mateusfbsoares, you are using snap for Obsidian. Snap is a isolated/contained environment. It does not inherit any user changes. Thus the pip installation( and corresponding modules ) will never be visible to Obsidian

**Comment by twibiral** [comment] 2022-10-13 19:10
I will close this issue now. Please reopen it when the problem reoccurs.

**Closed by twibiral** 2022-10-13 19:10 UTC
Labels: bug
